/**
 * Created by mluc on 16-06-2016.
 */

package com.lundwall.beerallover;

import java.util.ArrayList;
import java.util.Collections;
import java.util.Comparator;

public class PutLande {
    public static ArrayList lav() {
        ArrayList l;
        l = new ArrayList<LandObj>();
        // l.add(new LandObj(0, "... select ...."));
        l.add(new LandObj(1, "Andorra", "AD"));
        l.add(new LandObj(2, "United Arab Emirates", "AE"));
        l.add(new LandObj(3, "Afghanistan", "AF"));
        l.add(new LandObj(4, "Antigua and Barbuda", "AG"));
        l.add(new LandObj(6, "Albania", "AL"));
        l.add(new LandObj(7, "Armenia", "AM"));
        l.add(new LandObj(8, "Angola", "AO"));
        l.add(new LandObj(10, "Argentina", "AR"));
        l.add(new LandObj(12, "Austria", "AT"));
        l.add(new LandObj(13, "Australia", "AU"));
        l.add(new LandObj(14, "Aruba", "AW"));
        l.add(new LandObj(15, "\u00c5land Islands", "AX"));
        l.add(new LandObj(16, "Azerbaijan", "AZ"));
        l.add(new LandObj(17, "Bosnia and Herzegovina", "BA"));
        l.add(new LandObj(18, "Barbados", "BB"));
        l.add(new LandObj(19, "Bangladesh", "BD"));
        l.add(new LandObj(20, "Belgium", "BE"));
        l.add(new LandObj(21, "Burkina Faso", "BF"));
        l.add(new LandObj(22, "Bulgaria", "BG"));
        l.add(new LandObj(23, "Bahrain", "BH"));
        l.add(new LandObj(24, "Burundi", "BI"));
        l.add(new LandObj(25, "Benin", "BJ"));
        l.add(new LandObj(27, "Bermuda", "BM"));
        l.add(new LandObj(28, "Brunei Darussalam", "BN"));
        l.add(new LandObj(29, "Bolivia", "BO"));
        l.add(new LandObj(31, "Brazil", "BR"));
        l.add(new LandObj(32, "Bahamas", "BS"));
        l.add(new LandObj(33, "Bhutan", "BT"));
        l.add(new LandObj(35, "Botswana", "BW"));
        l.add(new LandObj(36, "Belarus", "BY"));
        l.add(new LandObj(37, "Belize", "BZ"));
        l.add(new LandObj(38, "Canada", "CA"));
        // l.add(new LandObj(39, "Cocos (Keeling) Islands", "CC"));
        l.add(new LandObj(40, "Democratic Republic of Congo", "CD"));
        l.add(new LandObj(41, "Central African Republic", "CF"));
        l.add(new LandObj(42, "Congo", "CG"));
        l.add(new LandObj(43, "Switzerland", "CH"));
        l.add(new LandObj(44, "C\u00f4te d'Ivoire", "CI"));
        l.add(new LandObj(45, "Cook Islands", "CK"));
        l.add(new LandObj(46, "Chile", "CL"));
        l.add(new LandObj(47, "Cameroon", "CM"));
        l.add(new LandObj(48, "China", "CN"));
        l.add(new LandObj(49, "Colombia", "CO"));
        l.add(new LandObj(50, "Costa Rica", "CR"));
        l.add(new LandObj(51, "Cuba", "CU"));
        l.add(new LandObj(52, "Cape Verde", "CV"));
        l.add(new LandObj(53, "Cura\u00e7ao", "CW"));
        l.add(new LandObj(55, "Cyprus", "CY"));
        l.add(new LandObj(56, "Czech Republic", "CZ"));
        l.add(new LandObj(57, "Germany", "DE"));
        l.add(new LandObj(58, "Djibouti", "DJ"));
        l.add(new LandObj(59, "Denmark", "DK"));
        l.add(new LandObj(60, "Dominica", "DM"));
        l.add(new LandObj(61, "Dominican Republic", "DO"));
        l.add(new LandObj(62, "Algeria", "DZ"));
        l.add(new LandObj(63, "Ecuador", "EC"));
        l.add(new LandObj(64, "Estonia", "EE"));
        l.add(new LandObj(65, "Egypt", "EG"));
        l.add(new LandObj(67, "Eritrea", "ER"));
        l.add(new LandObj(68, "Spain", "ES"));
        l.add(new LandObj(69, "Ethiopia", "ET"));
        l.add(new LandObj(70, "Finland", "FI"));
        l.add(new LandObj(71, "Fiji", "FJ"));
        l.add(new LandObj(72, "Falkland Islands", "FK"));
        l.add(new LandObj(73, "Federated States of Micronesia", "FM"));
        l.add(new LandObj(74, "Faroe Islands", "FO"));
        l.add(new LandObj(75, "France", "FR"));
        l.add(new LandObj(76, "Gabon", "GA"));
        l.add(new LandObj(77, "United Kingdom", "GB"));
        l.add(new LandObj(78, "Grenada", "GD"));
        l.add(new LandObj(79, "Georgia", "GE"));
        l.add(new LandObj(80, "French Guiana", "GF"));
        l.add(new LandObj(81, "Guernsey", "GG"));
        l.add(new LandObj(82, "Ghana", "GH"));
        l.add(new LandObj(83, "Gibraltar", "GI"));
        l.add(new LandObj(84, "Greenland", "GL"));
        l.add(new LandObj(85, "Gambia", "GM"));
        l.add(new LandObj(86, "Guinea", "GN"));
        l.add(new LandObj(87, "Guadeloupe", "GP"));
        l.add(new LandObj(88, "Equatorial Guinea", "GQ"));
        l.add(new LandObj(89, "Greece", "GR"));
        l.add(new LandObj(91, "Guatemala", "GT"));
        l.add(new LandObj(92, "Guam", "GU"));
        l.add(new LandObj(93, "Guinea-Bissau", "GW"));
        l.add(new LandObj(94, "Guyana", "GY"));
        l.add(new LandObj(95, "Hong Kong", "HK"));
        l.add(new LandObj(97, "Honduras", "HN"));
        l.add(new LandObj(98, "Croatia", "HR"));
        l.add(new LandObj(99, "Haiti", "HT"));
        l.add(new LandObj(100, "Hungary", "HU"));
        l.add(new LandObj(101, "Indonesia", "ID"));
        l.add(new LandObj(102, "Ireland", "IE"));
        l.add(new LandObj(103, "Israel", "IL"));
        l.add(new LandObj(104, "Isle of Man", "IM"));
        l.add(new LandObj(105, "India", "IN"));
        l.add(new LandObj(107, "Iraq", "IQ"));
        l.add(new LandObj(108, "Iran", "IR"));
        l.add(new LandObj(109, "Iceland", "IS"));
        l.add(new LandObj(110, "Italy", "IT"));
        l.add(new LandObj(111, "Jersey", "JE"));
        l.add(new LandObj(112, "Jamaica", "JM"));
        l.add(new LandObj(113, "Jordan", "JO"));
        l.add(new LandObj(114, "Japan", "JP"));
        l.add(new LandObj(115, "Kenya", "KE"));
        l.add(new LandObj(116, "Kyrgyzstan", "KG"));
        l.add(new LandObj(117, "Cambodia", "KH"));
        l.add(new LandObj(118, "Kiribati", "KI"));
        l.add(new LandObj(119, "Comoros", "KM"));
        l.add(new LandObj(120, "Saint Kitts and Nevis", "KN"));
        l.add(new LandObj(121, "North Korea", "KP"));
        l.add(new LandObj(122, "South Korea", "KR"));
        l.add(new LandObj(123, "Kuwait", "KW"));
        l.add(new LandObj(124, "Cayman Islands", "KY"));
        l.add(new LandObj(125, "Kazakhstan", "KZ"));
        l.add(new LandObj(126, "Lao People's Democratic Republic", "LA"));
        l.add(new LandObj(127, "Lebanon", "LB"));
        l.add(new LandObj(128, "Saint Lucia", "LC"));
        l.add(new LandObj(129, "Liechtenstein", "LI"));
        l.add(new LandObj(130, "Sri Lanka", "LK"));
        l.add(new LandObj(131, "Liberia", "LR"));
        l.add(new LandObj(132, "Lesotho", "LS"));
        l.add(new LandObj(133, "Lithuania", "LT"));
        l.add(new LandObj(134, "Luxembourg", "LU"));
        l.add(new LandObj(135, "Latvia", "LV"));
        l.add(new LandObj(136, "Libya", "LY"));
        l.add(new LandObj(137, "Morocco", "MA"));
        l.add(new LandObj(138, "Monaco", "MC"));
        l.add(new LandObj(139, "Moldova", "MD"));
        l.add(new LandObj(140, "Montenegro", "ME"));
        l.add(new LandObj(142, "Madagascar", "MG"));
        l.add(new LandObj(143, "Marshall Islands", "MH"));
        l.add(new LandObj(144, "Macedonia", "MK"));
        l.add(new LandObj(145, "Mali", "ML"));
        l.add(new LandObj(146, "Myanmar", "MM"));
        l.add(new LandObj(147, "Mongolia", "MN"));
        l.add(new LandObj(148, "Macau", "MO"));
        l.add(new LandObj(150, "Martinique", "MQ"));
        l.add(new LandObj(151, "Mauritania", "MR"));
        l.add(new LandObj(153, "Malta", "MT"));
        l.add(new LandObj(154, "Mauritius", "MU"));
        l.add(new LandObj(155, "Maldives", "MV"));
        l.add(new LandObj(156, "Malawi", "MW"));
        l.add(new LandObj(157, "Mexico", "MX"));
        l.add(new LandObj(158, "Malaysia", "MY"));
        l.add(new LandObj(159, "Mozambique", "MZ"));
        l.add(new LandObj(160, "Namibia", "NA"));
        l.add(new LandObj(161, "New Caledonia", "NC"));
        l.add(new LandObj(162, "Niger", "NE"));
        l.add(new LandObj(164, "Nigeria", "NG"));
        l.add(new LandObj(165, "Nicaragua", "NI"));
        l.add(new LandObj(166, "The Netherlands", "NL"));
        l.add(new LandObj(167, "Norway", "NO"));
        l.add(new LandObj(168, "Nepal", "NP"));
        l.add(new LandObj(169, "Nauru", "NR"));
        l.add(new LandObj(171, "New Zealand", "NZ"));
        l.add(new LandObj(172, "Oman", "OM"));
        l.add(new LandObj(173, "Panama", "PA"));
        l.add(new LandObj(174, "Peru", "PE"));
        l.add(new LandObj(175, "French Polynesia", "PF"));
        l.add(new LandObj(176, "Papua New Guinea", "PG"));
        l.add(new LandObj(177, "Philippines", "PH"));
        l.add(new LandObj(178, "Pakistan", "PK"));
        l.add(new LandObj(179, "Poland", "PL"));
        l.add(new LandObj(182, "Puerto Rico", "PR"));
        l.add(new LandObj(183, "Palestine", "PS"));
        l.add(new LandObj(184, "Portugal", "PT"));
        l.add(new LandObj(185, "Palau", "PW"));
        l.add(new LandObj(186, "Paraguay", "PY"));
        l.add(new LandObj(187, "Qatar", "QA"));
        l.add(new LandObj(188, "R\u00e9union", "RE"));
        l.add(new LandObj(189, "Romania", "RO"));
        l.add(new LandObj(190, "Serbia", "RS"));
        l.add(new LandObj(191, "Russian Federation", "RU"));
        l.add(new LandObj(192, "Rwanda", "RW"));
        l.add(new LandObj(193, "Saudi Arabia", "SA"));
        l.add(new LandObj(194, "Solomon Islands", "SB"));
        l.add(new LandObj(195, "Seychelles", "SC"));
        l.add(new LandObj(196, "Sudan", "SD"));
        l.add(new LandObj(197, "Sweden", "SE"));
        l.add(new LandObj(198, "Singapore", "SG"));
        l.add(new LandObj(200, "Slovenia", "SI"));
        l.add(new LandObj(201, "Svalbard and Jan Mayen Islands", "SJ"));
        l.add(new LandObj(202, "Slovakia", "SK"));
        l.add(new LandObj(203, "Sierra Leone", "SL"));
        l.add(new LandObj(204, "San Marino", "SM"));
        l.add(new LandObj(205, "Senegal", "SN"));
        l.add(new LandObj(206, "Somalia", "SO"));
        l.add(new LandObj(207, "Suriname", "SR"));
        l.add(new LandObj(208, "South Sudan", "SS"));
        l.add(new LandObj(209, "Sao Tome and Principe", "ST"));
        l.add(new LandObj(210, "El Salvador", "SV"));
        l.add(new LandObj(212, "Syria", "SY"));
        l.add(new LandObj(213, "Swaziland", "SZ"));
        l.add(new LandObj(214, "Turks and Caicos Islands", "TC"));
        l.add(new LandObj(215, "Chad", "TD"));
        l.add(new LandObj(217, "Togo", "TG"));
        l.add(new LandObj(218, "Thailand", "TH"));
        l.add(new LandObj(219, "Tajikistan", "TJ"));
        l.add(new LandObj(221, "Timor-Leste", "TL"));
        l.add(new LandObj(222, "Turkmenistan", "TM"));
        l.add(new LandObj(223, "Tunisia", "TN"));
        l.add(new LandObj(224, "Tonga", "TO"));
        l.add(new LandObj(225, "Turkey", "TR"));
        l.add(new LandObj(226, "Trinidad and Tobago", "TT"));
        l.add(new LandObj(227, "Tuvalu", "TV"));
        l.add(new LandObj(228, "Taiwan", "TW"));
        l.add(new LandObj(229, "Tanzania", "TZ"));
        l.add(new LandObj(230, "Ukraine", "UA"));
        l.add(new LandObj(231, "Uganda", "UG"));
        l.add(new LandObj(233, "United States", "US"));
        l.add(new LandObj(234, "Uruguay", "UY"));
        l.add(new LandObj(235, "Uzbekistan", "UZ"));
        l.add(new LandObj(236, "Vatican", "VA"));
        l.add(new LandObj(237, "Saint Vincent and the Grenadines", "VC"));
        l.add(new LandObj(238, "Venezuela", "VE"));
        l.add(new LandObj(240, "Virgin Islands (U.S)", "VI"));
        l.add(new LandObj(241, "Vietnam", "VN"));
        l.add(new LandObj(242, "Vanuatu", "VU"));
        l.add(new LandObj(244, "Samoa", "WS"));
        l.add(new LandObj(245, "Yemen", "YE"));
        l.add(new LandObj(246, "Mayotte", "YT"));
        l.add(new LandObj(247, "South Africa", "ZA"));
        l.add(new LandObj(248, "Zambia", "ZM"));
        l.add(new LandObj(249, "Zimbabwe", "ZW"));

        Collections.sort(l, new Comparator<LandObj>() {
            @Override
            public int compare(LandObj l1, LandObj l2) {
                return l1.Navn.compareTo(l2.Navn);
            }
        });

        return l;
    }

}